### ISSUE TITLE
Remove old piece icons

### ISSUE THREAD

**Issue by melvic-ybanez** [melvic-ybanez/Nostalgia#4]
We are now using new piece assets from [Phobos](https://itch.io/profile/phobos). We can remove the old assets, **except for the white knight** since we are using it as the app's icon for now.

**Comment by morrme** [comment]
Hi! I am able to help. Are these the ones you want removed? 
black_bishop.png
black_king.png
black_knight.png
black_pawn.png
black_queen.png
black_rook.png
white_bishop.png
white_king.png
white_pawn.png
white_queen.png
white_rook.png

**Comment by melvic-ybanez** [comment]
@morrme Yes. Thank you.
